name: CMake

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  CTEST_PARALLEL_LEVEL: 5

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bring runner env vars to workflows
        shell: bash
        run: |
          echo "local_app_data=$LOCALAPPDATA" >> $GITHUB_ENV
          echo "vcpkg_root=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV
          vcpkg x-history icu | awk 'NR==2{ print "icu_ver="$1 }' >> $GITHUB_ENV
          vcpkg x-history catch2 | awk 'NR==2{ print "catch2_ver="$1 }' >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          # use backslashes in path here for Windows.
          path: ${{ env.local_app_data }}\vcpkg\archives
          key: windows-vcpkg-cache-${{ env.icu_ver }}-${{ env.catch2_ver }}
          restore-keys: windows-vcpkg-cache-

      - name: Pull Vcpkg dependencies
        run: vcpkg install icu catch2 --triplet=x64-windows

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        env:
          CMAKE_TOOLCHAIN_FILE: ${{ env.vcpkg_root }}/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - uses: actions/upload-artifact@v2
        with:
          name: nuspell
          path: D:\a\nuspell\nuspell\build\src\tools\Release\*
